# Generated by Django 4.0.4 on 2022-05-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='user_id',
            new_name='user',
        ),
    ]
