# Generated by Django 4.0.4 on 2022-05-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_country_id_tickets_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.TextField(),
        ),
    ]
