# Generated by Django 4.0.4 on 2022-05-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tickets_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
