# Generated by Django 4.0.4 on 2022-05-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
