# Generated by Django 4.0.4 on 2022-05-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
